server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/social_media_platform
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update    # dev only, prod ??i qua Flyway
    properties.hibernate.format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health,info

cloudinary:
  cloud-name: dfvq2ckbi
  api-key: 283211323636595
  api-secret: pGxOZ7KcTVk76ETXvGsiWgPYtLQ


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
